// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: stringstream.proto

package stringstreampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StringStreamService_SendStrings_FullMethodName = "/stringstream.StringStreamService/SendStrings"
)

// StringStreamServiceClient is the client API for StringStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StringStreamServiceClient interface {
	SendStrings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StringMessage, StreamResponse], error)
}

type stringStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStringStreamServiceClient(cc grpc.ClientConnInterface) StringStreamServiceClient {
	return &stringStreamServiceClient{cc}
}

func (c *stringStreamServiceClient) SendStrings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StringMessage, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StringStreamService_ServiceDesc.Streams[0], StringStreamService_SendStrings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StringMessage, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StringStreamService_SendStringsClient = grpc.ClientStreamingClient[StringMessage, StreamResponse]

// StringStreamServiceServer is the server API for StringStreamService service.
// All implementations must embed UnimplementedStringStreamServiceServer
// for forward compatibility.
type StringStreamServiceServer interface {
	SendStrings(grpc.ClientStreamingServer[StringMessage, StreamResponse]) error
	mustEmbedUnimplementedStringStreamServiceServer()
}

// UnimplementedStringStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStringStreamServiceServer struct{}

func (UnimplementedStringStreamServiceServer) SendStrings(grpc.ClientStreamingServer[StringMessage, StreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendStrings not implemented")
}
func (UnimplementedStringStreamServiceServer) mustEmbedUnimplementedStringStreamServiceServer() {}
func (UnimplementedStringStreamServiceServer) testEmbeddedByValue()                             {}

// UnsafeStringStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StringStreamServiceServer will
// result in compilation errors.
type UnsafeStringStreamServiceServer interface {
	mustEmbedUnimplementedStringStreamServiceServer()
}

func RegisterStringStreamServiceServer(s grpc.ServiceRegistrar, srv StringStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedStringStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StringStreamService_ServiceDesc, srv)
}

func _StringStreamService_SendStrings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StringStreamServiceServer).SendStrings(&grpc.GenericServerStream[StringMessage, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StringStreamService_SendStringsServer = grpc.ClientStreamingServer[StringMessage, StreamResponse]

// StringStreamService_ServiceDesc is the grpc.ServiceDesc for StringStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StringStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stringstream.StringStreamService",
	HandlerType: (*StringStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStrings",
			Handler:       _StringStreamService_SendStrings_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "stringstream.proto",
}
