// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: stringstream.proto

package stringstreampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMessage) Reset() {
	*x = StringMessage{}
	mi := &file_stringstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMessage) ProtoMessage() {}

func (x *StringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_stringstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMessage.ProtoReflect.Descriptor instead.
func (*StringMessage) Descriptor() ([]byte, []int) {
	return file_stringstream_proto_rawDescGZIP(), []int{0}
}

func (x *StringMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_stringstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stringstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_stringstream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_stringstream_proto protoreflect.FileDescriptor

const file_stringstream_proto_rawDesc = "" +
	"\n" +
	"\x12stringstream.proto\x12\fstringstream\"#\n" +
	"\rStringMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"(\n" +
	"\x0eStreamResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2a\n" +
	"\x13StringStreamService\x12J\n" +
	"\vSendStrings\x12\x1b.stringstream.StringMessage\x1a\x1c.stringstream.StreamResponse(\x01B\x1cZ\x1a../grpcfile;stringstreampbb\x06proto3"

var (
	file_stringstream_proto_rawDescOnce sync.Once
	file_stringstream_proto_rawDescData []byte
)

func file_stringstream_proto_rawDescGZIP() []byte {
	file_stringstream_proto_rawDescOnce.Do(func() {
		file_stringstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stringstream_proto_rawDesc), len(file_stringstream_proto_rawDesc)))
	})
	return file_stringstream_proto_rawDescData
}

var file_stringstream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stringstream_proto_goTypes = []any{
	(*StringMessage)(nil),  // 0: stringstream.StringMessage
	(*StreamResponse)(nil), // 1: stringstream.StreamResponse
}
var file_stringstream_proto_depIdxs = []int32{
	0, // 0: stringstream.StringStreamService.SendStrings:input_type -> stringstream.StringMessage
	1, // 1: stringstream.StringStreamService.SendStrings:output_type -> stringstream.StreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stringstream_proto_init() }
func file_stringstream_proto_init() {
	if File_stringstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stringstream_proto_rawDesc), len(file_stringstream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stringstream_proto_goTypes,
		DependencyIndexes: file_stringstream_proto_depIdxs,
		MessageInfos:      file_stringstream_proto_msgTypes,
	}.Build()
	File_stringstream_proto = out.File
	file_stringstream_proto_goTypes = nil
	file_stringstream_proto_depIdxs = nil
}
